# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-21 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_auto_20171021_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='greeting',
            name='my_field',
            field=models.TextField(default='bjarne', max_length=50),
        ),
    ]
